# Безопасность
loopback_users.guest = false

# Сетевые настройки
listeners.tcp.default = 5672
management.tcp.port = 15672
management.tcp.ip = 0.0.0.0

# Количество сетевых потоков
num_acceptors.tcp = 10

# Логирование
log.console = true
log.console.level = info

# Персистентность
queue_master_locator = min-masters
disk_free_limit.absolute = 2GB
